# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-06 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co2_saved', models.FloatField()),
                ('milage', models.FloatField()),
                ('money_saved', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=20)),
                ('number', models.IntegerField()),
                ('question_title', models.TextField(max_length=500)),
                ('right_answer', models.CharField(max_length=128)),
                ('wrong_answer1', models.CharField(max_length=128)),
                ('wrong_answer2', models.CharField(max_length=128)),
                ('wrong_answer3', models.CharField(max_length=128)),
            ],
        ),
    ]
