# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-06 06:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co2_saved', models.FloatField(default=0)),
                ('milage', models.FloatField()),
                ('money_saved', models.FloatField(default=0)),
                ('created', models.DateTimeField(null=True)),
                ('complete_in', models.IntegerField(default=30)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=20)),
                ('number', models.IntegerField()),
                ('question_title', models.TextField(max_length=500)),
                ('right_answer', models.CharField(max_length=128)),
                ('wrong_answer1', models.CharField(max_length=128)),
                ('wrong_answer2', models.CharField(max_length=128)),
                ('wrong_answer3', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='UserProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='brake_classroom.Project')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
