# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-05 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brake_classroom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co2_saved', models.FloatField()),
                ('milage', models.FloatField()),
                ('money_saved', models.FloatField()),
            ],
        ),
    ]
